"""empty message

Revision ID: 472c8c7f4209
Revises: None
Create Date: 2016-06-21 12:46:06.145890

"""

# revision identifiers, used by Alembic.
revision = '472c8c7f4209'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followed_tickers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followed_tickers', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
