"""empty message

Revision ID: b8d688616685
Revises: dbec2342ffea
Create Date: 2016-06-22 08:37:16.883383

"""

# revision identifiers, used by Alembic.
revision = 'b8d688616685'
down_revision = 'dbec2342ffea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
