"""empty message

Revision ID: dbec2342ffea
Revises: 472c8c7f4209
Create Date: 2016-06-21 21:50:59.028234

"""

# revision identifiers, used by Alembic.
revision = 'dbec2342ffea'
down_revision = '472c8c7f4209'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    ### end Alembic commands ###
