"""empty message

Revision ID: e7edb9eb5994
Revises: None
Create Date: 2016-06-09 15:08:04.406937

"""

# revision identifiers, used by Alembic.
revision = 'e7edb9eb5994'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followed_tickers', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followed_tickers')
    ### end Alembic commands ###
