"""empty message

Revision ID: f76ed87773c2
Revises: e7edb9eb5994
Create Date: 2016-06-09 15:23:19.279129

"""

# revision identifiers, used by Alembic.
revision = 'f76ed87773c2'
down_revision = 'e7edb9eb5994'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('followed_tickers', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey')

    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'])
    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_constraint(u'posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    )
    ### end Alembic commands ###
